# WORKSHOP NUMPY

## Statistiques d'engagement

In [2084]:
import numpy as np
import pandas as pd

### Visualisation of Data : 

#### 1/- Reply

In [2085]:
reply = np.array([(1,5,5,0,3),(2,0,5,0,3),(0,0,0,0,0),(2,0,0,4,0),(0,4,2,0,0)])
reply

array([[1, 5, 5, 0, 3],
       [2, 0, 5, 0, 3],
       [0, 0, 0, 0, 0],
       [2, 0, 0, 4, 0],
       [0, 4, 2, 0, 0]])

#### 2/- Retweet

In [2086]:
retweet = np.array([(0,2,4,0,0),(0,0,0,0,0),(0,0,0,0,0),(0,0,0,4,3),(0,2,5,0,0)])
retweet

array([[0, 2, 4, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 4, 3],
       [0, 2, 5, 0, 0]])

#### 3/- Like

In [2087]:
like = np.array([(2,5,1,0,3),(0,0,0,0,0),(0,5,0,3,3),(1,0,0,4,1),(0,0,9,0,0)])
like

array([[2, 5, 1, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 5, 0, 3, 3],
       [1, 0, 0, 4, 1],
       [0, 0, 9, 0, 0]])

#### 4/- Tweets

In [2088]:
tweets = np.array([2, 5, 10, 4, 3])
tweets

array([ 2,  5, 10,  4,  3])

#### 5/- Users

In [2089]:
appUsers = [0, 1, 2, 3, 4]

### Answering Question

#### 1/- User with max Replies

In [2090]:
def maxUser(tab):
    user = np.argmax(tab.cumsum(axis=1)[:,-1],axis=0)
    value = tab.max(axis=1)[user]
    return user,value


In [2091]:
user,value=maxUser(reply)
print("The user with the most replies is ", user)
print("with a value of : ",value)

The user with the most replies is  0
with a value of :  5


#### 2/- User with max Retweets

In [2092]:
user,value=maxUser(retweet)
print("The user with the most retweets is ", user)
print("with a value of : ",value)

The user with the most retweets is  3
with a value of :  4


#### 3/- Users that does neither Reply nor Retweet

In [2093]:
def getOnCond(table,cond):
    arr = table.cumsum(axis=1)[:,-1]
    res= np.array(np.where(arr==cond))
    return res[0].tolist()

In [2094]:
def intersection(lst1, lst2):
    lst3 = [value for value in lst1 if value in lst2]
    return lst3

In [2095]:
def elementFromList(table,index):
    tmp = []
    for i in index :
        tmp.append(table[i])
    return tmp

In [2096]:
user=getOnCond(reply,0)
print("The users with no replies are ", user)

user2=getOnCond(retweet,0)

print("The users with no retweets are ", user2)

users = elementFromList(appUsers,intersection(user,user2))

print("The users with neither replies nor retweets are : ", users)

The users with no replies are  [2]
The users with no retweets are  [1, 2]
The users with neither replies nor retweets are :  [2]


#### 4/- Number of likes that every user has given himself :

In [2097]:
def getDiag(matrix):
    diag = []
    i=0
    while (i < len(matrix[0])):
        j=0
        while( j < len(matrix[1])):
            if(i==j):
                diag.append({"user":i,"nbLikes":matrix[i][j]})
            j+=1
        i+=1
    return diag

In [2098]:
listLikes=getDiag(like)
print("Number of likes that every user has given himself : ")
for elem in listLikes :
    print("user : ", elem["user"], " number of likes : ", elem["nbLikes"])

Number of likes that every user has given himself : 
user :  0  number of likes :  2
user :  1  number of likes :  0
user :  2  number of likes :  0
user :  3  number of likes :  4
user :  4  number of likes :  0


#### 5/- Number of Likes of each user for other users beside himself :

In [2099]:
tmp = like.cumsum(axis=1)[:,-1]
likeOtherUsers = [{"user":i,"nbLikes":value-listLikes[i]["nbLikes"]} for i,value in enumerate(tmp)]
print("Number of likes that every user has given to other users : ")
for elem in likeOtherUsers :
    print("user : ", elem["user"], " number of likes : ", elem["nbLikes"])

Number of likes that every user has given to other users : 
user :  0  number of likes :  9
user :  1  number of likes :  0
user :  2  number of likes :  11
user :  3  number of likes :  2
user :  4  number of likes :  9


#### 6/- The users that like their own tweets more than the other's

In [2100]:
ownLikeMore = []
for i,elem in enumerate(likeOtherUsers):
    if(listLikes[i]["nbLikes"] > elem["nbLikes"]):
        ownLikeMore.append(elem)
ownLikeMore

[{'user': 3, 'nbLikes': 2}]

#### 7/- The number of those users : 

In [2101]:
len(ownLikeMore)

1

#### 8/- Number of Interactions of each user :

In [2102]:
tmp_interactions = (like+reply+retweet).cumsum(axis=1)[:,-1]
interactions = []
for i,inter in enumerate(tmp_interactions):
    interactions.append({"user":i,"nbInteractions":inter})
for elem in interactions :
    print("user : ", elem["user"], " number of interactions : ", elem["nbInteractions"])

user :  0  number of interactions :  31
user :  1  number of interactions :  10
user :  2  number of interactions :  11
user :  3  number of interactions :  19
user :  4  number of interactions :  22


## Statistiques sur les interactions

#### 1/-Number of likes of each user :

In [2103]:
nbLikeAllUsers = like*(1-np.eye(len(like))).astype(int)
nbLikeAllUsers.cumsum(axis=0)[-1,:]
tmp = []
for i,inter in enumerate(tmp_interactions):
    tmp.append({"user":i,"nbLikes":inter})
for elem in tmp :
    print("user : ", elem["user"], " has recieved in total : ", elem["nbLikes"]," likes")

user :  0  has recieved in total :  31  likes
user :  1  has recieved in total :  10  likes
user :  2  has recieved in total :  11  likes
user :  3  has recieved in total :  19  likes
user :  4  has recieved in total :  22  likes


#### 2/- Users that liked all the tweets of other users :

In [2104]:

## A REFAIRE ##
tmp = like*(1-np.eye(len(like))).astype(int)
tmp_x = tweets
tmp_k=[]
i=0
tmp_x= tweets
tmp_k=(tweets == tmp)*(tmp_x>0)
while(i<len(tweets)):
    print(tmp_k[:,i])
    print("The users that like all the tweets of the user ", i, " are : ",np.array(np.where(tmp_k[:,i]==True))[0])
    i+=1


[False False False False False]
The users that like all the tweets of the user  0  are :  []
[ True False  True False False]
The users that like all the tweets of the user  1  are :  [0 2]
[False False False False False]
The users that like all the tweets of the user  2  are :  []
[False False False False False]
The users that like all the tweets of the user  3  are :  []
[ True False  True False False]
The users that like all the tweets of the user  4  are :  [0 2]


#### 3+4/- Number of Outgoing and Incoming arcs :

In [2105]:
sumMatrix = reply+retweet+like
tmp_arcs = np.array(np.where(sumMatrix>0))
tmp_out=tmp_arcs[0]
tmp_in=tmp_arcs[1]

In [2106]:
def getOccuElem(table1,table2):
    tmp = []
    i=0
    while(i<len(tweets)) :
        tmp.append({"user":i,"nbIncomingArcs":np.count_nonzero(table1 == i),"nbOutgoingArcs":np.count_nonzero(table2 == i)})
        i+=1
    return tmp


In [2107]:
arcs = getOccuElem(tmp_in,tmp_out)
arcs

[{'user': 0, 'nbIncomingArcs': 3, 'nbOutgoingArcs': 4},
 {'user': 1, 'nbIncomingArcs': 3, 'nbOutgoingArcs': 3},
 {'user': 2, 'nbIncomingArcs': 3, 'nbOutgoingArcs': 3},
 {'user': 3, 'nbIncomingArcs': 2, 'nbOutgoingArcs': 3},
 {'user': 4, 'nbIncomingArcs': 4, 'nbOutgoingArcs': 2}]

#### 5/- The nodes (Users) that have the name number of Incoming and Outgoing Arcs :

In [2108]:
equiNodesInteractions = []
for elem in arcs :
    if(elem["nbIncomingArcs"] == elem["nbOutgoingArcs"]):
        equiNodesInteractions.append(elem)
equiNodesInteractions

[{'user': 1, 'nbIncomingArcs': 3, 'nbOutgoingArcs': 3},
 {'user': 2, 'nbIncomingArcs': 3, 'nbOutgoingArcs': 3}]

#### 6/- The Likes between those who have the same number of Incoming and Outgoing Arcs :

In [2109]:
tmp_arcs
tmp_x = intersection(np.array(np.where(tmp_arcs[0]==1))[0],np.array(np.where(tmp_arcs[1]==2))[0])
list1 = elementFromList(tmp_arcs[0],tmp_x)
list2 = elementFromList(tmp_arcs[1],tmp_x)
for i,elem in enumerate(list1) :
    print("The users : ",elem," and ",list2[i], " did like eeach other's tweet")

The users :  1  and  2  did like eeach other's tweet


## Popularity

In [2110]:
tmp_like = like*(1-np.eye(len(appUsers))).astype(int)
tmp_reply = reply*(1-np.eye(len(appUsers))).astype(int)

#### 1/- Score Reply :

In [2111]:
sumLike=tmp_like.cumsum(axis=1)[:,-1]
sumReply=tmp_reply.cumsum(axis=1)[:,-1]
scoreReply = np.array(np.where(sumReply<sumLike,sumReply*0,0))+np.array(np.where(sumReply==sumLike,sumReply*-0.25,0))+np.array(np.where(sumReply>sumLike,sumReply*-0.5,0))
scoreReply

array([-6.5, -5. ,  0. , -0.5,  0. ])

#### 2/- Score Retweet :

In [2112]:
diag = getDiag(retweet)
diagRetweet = []
for elem in diag :
    diagRetweet.append(elem["nbLikes"])
scoreRetweet = retweet.cumsum(axis=1)[:,-1]
scoreRetweet = np.where(np.array(diagRetweet)>0,scoreRetweet,scoreRetweet*-0.25)
scoreRetweet

array([-1.5 , -0.  , -0.  ,  7.  , -1.75])

#### 3/- Score Like :

In [2113]:
sumLikeRecieved=like.cumsum(axis=0)[-1,:]
scoreLike = np.array(np.where(sumLikeRecieved>(tweets/2),sumLikeRecieved*1.5,sumLikeRecieved))
scoreLike

array([ 4.5, 15. , 15. , 10.5, 10.5])

#### 4/- Score of each user :

In [2114]:
scoreUser = []
for i,elem in enumerate(appUsers) :
    scoreUser.append({"user":i,"scoreTotal":(scoreReply[i]+scoreRetweet[i]+scoreLike[i])/3})
scoreUser

[{'user': 0, 'scoreTotal': -1.1666666666666667},
 {'user': 1, 'scoreTotal': 3.3333333333333335},
 {'user': 2, 'scoreTotal': 5.0},
 {'user': 3, 'scoreTotal': 5.666666666666667},
 {'user': 4, 'scoreTotal': 2.9166666666666665}]

#### 5/- Score Total :

In [2115]:
scoreTotal = (scoreLike.sum()/len(scoreLike)+scoreReply.sum()/len(scoreReply)+scoreRetweet.sum()/len(scoreRetweet))/3
scoreTotal

3.15